# script to return the middle text of a file
# created 09/27/2024
# generated by Zane Gray
#
# Usage:
# include in first position, file path and name via command line

head -n "$2" "$1" | tail -n "$3"

